import { readdirSync, readFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join, dirname, basename, extname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const RELEASE_DIR = join(__dirname, '../../docs/releases')
const OUT_DIR = join(__dirname, '../src/generated')
const OUT_FILE = join(OUT_DIR, 'release-notes.ts')

export interface ReleaseNote {
  version: string
  date?: string
  title: string
  body: string
}

function parseSemver(fileName: string): string | null {
  const base = basename(fileName, extname(fileName))
  const m = base.match(/^v(\d+\.\d+\.\d+)$/)
  return m ? m[1]! : null
}

function compareSemver(a: string, b: string): number {
  const pa = a.split('.').map(Number)
  const pb = b.split('.').map(Number)
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const na = pa[i] ?? 0
    const nb = pb[i] ?? 0
    if (na !== nb) return nb - na
  }
  return b.localeCompare(a)
}

function parseNote(content: string, version: string): ReleaseNote {
  const lines = content.split(/\r?\n/)
  let title = `v${version}`
  let date: string | undefined
  let titleEndIdx = 0

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!
    const titleMatch = line.match(/^#\s+(.+)$/)
    if (titleMatch && title === `v${version}`) {
      title = titleMatch[1]!.trim()
      titleEndIdx = i + 1
      continue
    }
    const dateMatch = line.match(/^>\s*日期[:：]\s*(\d{4}-\d{2}-\d{2})/)
    if (dateMatch && !date) {
      date = dateMatch[1]
    }
  }

  const body = lines
    .slice(titleEndIdx)
    .join('\n')
    .replace(/^\s+/, '')

  return { version, date, title, body }
}

function build(): void {
  if (!existsSync(RELEASE_DIR)) {
    console.warn(`[release-notes] ${RELEASE_DIR} not found, generating empty bundle`)
    mkdirSync(OUT_DIR, { recursive: true })
    writeFileSync(OUT_FILE, 'export interface ReleaseNote { version: string; date?: string; title: string; body: string }\nexport const RELEASE_NOTES: ReleaseNote[] = []\n')
    return
  }

  const files = readdirSync(RELEASE_DIR).filter((f) => f.endsWith('.md'))
  const notes: ReleaseNote[] = []

  for (const file of files) {
    const version = parseSemver(file)
    if (!version) continue
    const content = readFileSync(join(RELEASE_DIR, file), 'utf-8')
    notes.push(parseNote(content, version))
  }

  notes.sort((a, b) => compareSemver(a.version, b.version))

  const serialized = notes.map((n) => {
    const fields = [
      `version: ${JSON.stringify(n.version)}`,
      n.date ? `date: ${JSON.stringify(n.date)}` : '',
      `title: ${JSON.stringify(n.title)}`,
      `body: ${JSON.stringify(n.body)}`,
    ].filter(Boolean)
    return `  { ${fields.join(', ')} }`
  })

  const code = `// Auto-generated by scripts/build-release-notes.ts
// Do not edit manually.

export interface ReleaseNote {
  version: string
  date?: string
  title: string
  body: string
}

export const RELEASE_NOTES: ReleaseNote[] = [\n${serialized.join(',\n')}\n]\n`

  mkdirSync(OUT_DIR, { recursive: true })
  writeFileSync(OUT_FILE, code)
  console.log(`[release-notes] generated ${notes.length} notes → src/generated/release-notes.ts`)
}

build()
