import type { Config } from './schema.js'

export const DEFAULT_CONFIG: Config = {
  editor: {},
  provider: {
    default: 'deepseek',
    providers: {
      deepseek: {
        name: 'deepseek',
        apiKeyEnv: 'DEEPSEEK_API_KEY',
        baseUrl: 'https://api.deepseek.com/v1',
        protocol: 'openai' as const,
        capabilities: {
          cacheControl: false,
          stripParams: [],
          toolJsonBug: true,
          prefixCache: 'deepseek-native' as const,
          prefixCompletion: true,
        },
        thinking: 'enabled',
        maxTokens: 64000,
        models: [
          {
            id: 'deepseek-v4-pro',
            alias: 'v4-pro',
            contextWindow: 1_000_000,
            maxTokens: 163_000,
            reasoningEffort: 'max',
          },
          {
            id: 'deepseek-v4-flash',
            alias: 'v4-flash',
            contextWindow: 1_000_000,
            maxTokens: 163_000,
            reasoningEffort: 'high',
          },
        ],
        unsupported: [],
      },
      kimi: {
        name: 'kimi',
        apiKeyEnv: 'KIMI_API_KEY',
        baseUrl: 'https://api.kimi.com/coding/v1',
        protocol: 'openai' as const,
        capabilities: {
          cacheControl: false,
          stripParams: [],
          toolJsonBug: false,
          prefixCache: 'none' as const,
          prefixCompletion: false,
        },
        thinking: 'enabled',
        maxTokens: 64000,
        models: [
          {
            id: 'kimi-for-coding',
            alias: 'kimi',
            contextWindow: 200_000,
            maxTokens: 64000,
            reasoningEffort: 'high',
          },
        ],
        unsupported: [],
      },
      glm: {
        name: 'glm',
        apiKeyEnv: 'ZHIPU_API_KEY',
        baseUrl: 'https://open.bigmodel.cn/api/coding/paas/v4',
        protocol: 'openai' as const,
        capabilities: {
          cacheControl: false,
          stripParams: [],
          toolJsonBug: false,
          prefixCache: 'none' as const,
          prefixCompletion: false,
        },
        thinking: 'enabled',
        maxTokens: 128000,
        models: [
          {
            id: 'glm-5.1',
            alias: 'glm',
            contextWindow: 200_000,
            maxTokens: 128000,
            reasoningEffort: 'high',
          },
        ],
        unsupported: ['stream_options'],
      },
      claude: {
        name: 'claude',
        apiKeyEnv: 'CLAUDE_API_KEY',
        baseUrl: 'http://85.137.242.133:8080/v1',
        protocol: 'openai' as const,
        capabilities: {
          cacheControl: false,
          stripParams: [],
          toolJsonBug: false,
          prefixCache: 'none' as const,
          prefixCompletion: false,
        },
        thinking: 'enabled',
        maxTokens: 128000,
        models: [
          {
            id: 'claude-opus-4-7',
            alias: 'opus-4-7',
            contextWindow: 1_000_000,
            maxTokens: 128000,
            reasoningEffort: 'max',
          },
          {
            id: 'claude-opus-4-6',
            alias: 'opus-4-6',
            contextWindow: 1_000_000,
            maxTokens: 128000,
            reasoningEffort: 'max',
          },
          {
            id: 'claude-sonnet-4-5',
            alias: 'sonnet-4-5',
            contextWindow: 1_000_000,
            maxTokens: 128000,
            reasoningEffort: 'max',
          },
        ],
        unsupported: [],
      },
      mimo: {
        name: 'mimo',
        apiKeyEnv: 'MIMO_API_KEY',
        baseUrl: 'https://token-plan-sgp.xiaomimimo.com/v1',
        protocol: 'openai' as const,
        capabilities: {
          cacheControl: false,
          stripParams: [],
          toolJsonBug: false,
          prefixCache: 'none' as const,
          prefixCompletion: false,
        },
        thinking: 'enabled',
        maxTokens: 64000,
        models: [
          {
            id: 'mimo-v2.5-pro',
            alias: 'mimo-pro',
            contextWindow: 1_000_000,
            maxTokens: 64000,
          },
          {
            id: 'mimo-v2.5',
            alias: 'mimo',
            contextWindow: 262_000,
            maxTokens: 64000,
          },
        ],
        unsupported: ['stream_options'],
      },
      minimax: {
        name: 'minimax',
        apiKeyEnv: 'MINIMAX_API_KEY',
        baseUrl: 'https://api.minimaxi.com/v1',
        protocol: 'openai' as const,
        capabilities: {
          cacheControl: false,
          stripParams: ['top_k', 'metadata', 'service_tier', 'cache_control'],
          toolJsonBug: false,
          prefixCache: 'none' as const,
          prefixCompletion: false,
        },
        thinking: 'enabled',
        maxTokens: 64000,
        models: [
          {
            id: 'MiniMax-M2.7',
            alias: 'minimax',
            contextWindow: 204_800,
            maxTokens: 64000,
          },
        ],
        unsupported: [],
      },
    },
  },
  agent: {
    approval: 'suggest',
    maxTurns: 50,
    mode: 'code',
    autoReasoning: false,
    permissions: {
      allow: [],
    },
  },
  compact: {
    enabled: true,
    autoThreshold: 800_000,
    autoFloor: 500_000,
    model: 'deepseek-v4-flash',
  },
  cache: {
    enabled: true,
    minSystemTokens: 256,
    showHitRate: true,
  },
  mcp: {
    enabled: true,
    servers: {},
  },
  workers: {
    profiles: {
      cheap: { provider: 'deepseek', model: 'deepseek-v4-flash' },
      'cheap-minimax': { provider: 'minimax', model: 'MiniMax-M2.7' },
      capable: { provider: 'deepseek', model: 'deepseek-v4-pro' },
      mimo: { provider: 'mimo', model: 'mimo-v2.5' },
      'mimo-pro': { provider: 'mimo', model: 'mimo-v2.5-pro' },
    },
    routing: {
      repo_summarization: 'cheap',
      code_edit: 'capable',
      test_failure_diagnosis: 'capable',
      risky_refactor: 'capable',
    },
  },
}
